In [1]:
import numpy as np
import math

In [8]:
np.random.rand() * np.random.randint(20)

17.65841316829893

In [12]:
cols = 8
X = np.random.randint(0, 10, size = (100,cols))
Y = np.zeros(100)
X

array([[5, 9, 9, 9, 4, 5, 9, 5],
       [0, 2, 1, 1, 4, 9, 6, 5],
       [7, 8, 8, 9, 6, 7, 8, 1],
       [5, 7, 2, 1, 3, 4, 7, 7],
       [7, 5, 3, 9, 1, 8, 6, 6],
       [3, 9, 9, 3, 8, 7, 1, 3],
       [4, 4, 2, 5, 5, 1, 6, 7],
       [6, 9, 9, 5, 9, 6, 1, 3],
       [9, 9, 1, 0, 0, 5, 4, 2],
       [7, 1, 8, 1, 4, 9, 4, 3],
       [0, 5, 7, 5, 4, 5, 1, 2],
       [5, 0, 2, 4, 1, 6, 5, 8],
       [2, 8, 0, 4, 0, 3, 4, 4],
       [4, 3, 9, 1, 3, 9, 4, 2],
       [7, 9, 3, 0, 0, 9, 8, 0],
       [9, 7, 0, 8, 1, 2, 4, 7],
       [8, 7, 1, 4, 0, 5, 4, 3],
       [9, 5, 2, 4, 3, 3, 5, 2],
       [3, 7, 1, 5, 1, 3, 2, 3],
       [2, 5, 2, 1, 1, 2, 7, 7],
       [0, 6, 0, 1, 5, 4, 3, 1],
       [5, 6, 6, 1, 0, 8, 3, 6],
       [4, 7, 2, 0, 3, 9, 5, 4],
       [0, 8, 6, 0, 6, 7, 6, 4],
       [9, 3, 5, 3, 1, 9, 5, 7],
       [3, 8, 7, 7, 0, 3, 3, 9],
       [1, 8, 2, 6, 0, 4, 1, 3],
       [7, 7, 4, 3, 3, 9, 1, 7],
       [5, 3, 9, 9, 8, 4, 7, 9],
       [2, 5, 7, 8, 3, 7, 0, 0],
       [2,

In [44]:
posit = np.random.rand()
print posit
weights = np.multiply(np.random.rand(X.shape[1]), np.random.randint(1, 10, size=(X.shape[1])))
weights

0.542541945934


array([3.28662463, 0.13893729, 3.6114073 , 0.76616815, 7.9841411 ,
       0.59814854, 4.6526233 , 4.84724911])

In [45]:
a = np.random.rand(weights.shape[0]) > 0.5
b = np.ones(weights.shape[0])
b[a==True] = -1
b

array([ 1., -1.,  1.,  1.,  1.,  1.,  1., -1.])

In [47]:
weights = weights * b
weights

array([ 3.28662463, -0.13893729,  3.6114073 ,  0.76616815,  7.9841411 ,
        0.59814854,  4.6526233 , -4.84724911])

In [48]:
type(weights)

numpy.ndarray

In [54]:
Y = np.dot(X, weights)
Y.shape

(100,)

In [55]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is returned if ``loc`

In [56]:
np.mean(Y)

65.33066031759053

In [58]:
Z = Y + np.random.normal(loc=0.0, scale=(np.mean(Y)/50), size=Y.shape[0])
Z

array([108.65837697,  49.07206853, 143.21119894,  47.95350424,
        52.20623749,  99.64021809,  57.15569692, 119.70437072,
        42.32468879,  91.28810948,  57.27002697,  21.11597743,
        11.58054162,  84.68443995,  76.55075093,  29.59502145,
        38.2525785 ,  78.98145353,  20.89950582,  21.36470488,
        51.55695613,  28.47795164,  53.94750879,  82.19723247,
        51.08366687,   9.50678005,   5.90966548,  39.16691621,
       110.01297442,  64.87180333,  79.07467619,  70.02272057,
        68.26754577,  96.04909893,  45.18108062,  11.42548711,
        88.76585308,  50.21847749,  17.97755206, 115.20670845,
       105.1694988 ,  46.58499126, 116.10793732,  45.75336306,
       136.62543259,  16.12633742,  24.40352299, 108.95293603,
        95.84481665,  82.01825537,  80.42830881, 102.35885814,
        17.28693198, 110.09919184,   5.63058422,  71.12637881,
        59.01729347,  60.09495   ,  85.69381532,  20.84268112,
        71.82140752,  46.75909071,  32.19942982,  90.59

In [59]:
Z - Y

array([ 1.51283907,  3.97297217,  1.06392936, -0.47867742,  0.56324171,
       -1.94143496, -0.99255785, -0.65548508, -1.52264226, -2.62539933,
       -1.03141066, -1.66278885,  2.03817568,  0.43416428,  1.35626894,
        0.99842799, -0.80342599,  0.49354389,  0.02785889, -0.32089818,
        0.20049125,  0.7842767 ,  1.34087647,  1.02165722, -1.13453457,
       -2.01169725, -0.58875451,  0.33133148, -0.61036001, -0.55541893,
        0.20951391, -0.97716611, -0.96173314,  1.88902696, -1.06966143,
       -1.31637231, -1.74957204,  0.97039211, -0.8529087 ,  0.30430329,
       -0.55432311,  3.62915069,  0.53980952,  0.73640234,  0.5682065 ,
        0.3728105 , -0.41652495, -1.22175716, -2.3044096 , -0.50848413,
       -1.07071728, -2.12570661, -0.07905898, -0.08723601,  0.92835998,
        1.58297423,  1.46395906, -1.9587925 , -0.19990696,  0.67899393,
        2.68667877,  3.00595382,  1.48855169, -0.35361788, -0.17012105,
        0.86580546,  1.04745599, -0.70184356, -0.22746203,  2.02

In [ ]:
c