In [3]:
import numpy as np
a = np.array([0, 0.5, 1., 1.5, 2.])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [5]:
b = np.array([a, a*2])
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [7]:
c = np.zeros((2,3,4), dtype='i', order='C')
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [8]:
d = np.ones_like(c, dtype='f16', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [11]:
np.sin(np.pi).round(10)

0.0