In [5]:
import pandas as pd
import numpy as np
import os

In [8]:

def get_learner_data_file(basefilename):
    return open(os.path.join(os.environ.get("LEARNER_DATA_DIR",'Data/'),basefilename),'r')



In [9]:
datafile = 'simple.csv'
with get_learner_data_file(datafile) as f:
    alldata = np.genfromtxt(f,delimiter=',')
    if datafile == 'Istanbul.csv':
        alldata = alldata[1:,1:]
    datasize = alldata.shape[0]
    # cutoff = int(datasize*0.6)
    # permutation = np.random.permutation(alldata.shape[0])
    # col_permutation = np.random.permutation(alldata.shape[1]-1)
    # train_data = alldata[permutation[:cutoff],:]
    # trainX = train_data[:,:-1]
    train_data = alldata
    trainX = train_data[:,:-1]
    trainY = train_data[:,-1]
    # testX = test_data[:,:-1]
    testX = trainX
    testY = testX

In [15]:
def get_best_corr(Xtrain, Ytrain):
    x = np.transpose(Xtrain)
    y = np.transpose(Ytrain)
    mat = np.corrcoef(x, y)
    mat = np.abs(mat[-1])
    return np.nanargmax(mat[:-1])

In [16]:
trainX

array([[1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [3., 3.],
       [5., 0.],
       [0., 5.]])

In [17]:
split_ind = get_best_corr(trainX, trainY)
split_ind

1

In [19]:
split_val = np.median(trainX[:,split_ind])

In [27]:
permed = np.random.randint(0, high=trainX.shape[0], size=(trainX.shape[0]))
permed


array([35, 46,  0,  2, 37, 14,  1, 40, 36, 35, 45, 42, 15, 47, 16,  9, 40,
       26,  3, 22, 28, 42, 35, 37, 18, 22,  5, 13,  0, 13, 44, 26, 27, 37,
       39,  7,  5, 35, 15, 47,  7, 13, 17, 23, 32, 15, 39, 38, 48,  9])

In [34]:
trainY[permed]

array([ 6.,  5.,  6., 10., 10., 11.,  5.,  6.,  5.,  6.,  6., 10.,  6.,
       10.,  5., 11.,  6.,  5.,  6., 10.,  6., 10.,  6., 10.,  6., 10.,
        6.,  6.,  6.,  6., 11.,  5., 10., 10., 11., 10.,  6.,  6.,  6.,
       10., 10.,  6., 10.,  6., 10.,  6., 11.,  6.,  6., 11.])

In [41]:
trainY[14]

11.0

In [28]:
trainX[permed, :]

array([[1., 2.],
       [2., 1.],
       [1., 2.],
       [3., 3.],
       [3., 3.],
       [0., 5.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [1., 2.],
       [1., 2.],
       [3., 3.],
       [1., 2.],
       [3., 3.],
       [2., 1.],
       [0., 5.],
       [1., 2.],
       [2., 1.],
       [5., 0.],
       [3., 3.],
       [5., 0.],
       [3., 3.],
       [1., 2.],
       [3., 3.],
       [5., 0.],
       [3., 3.],
       [1., 2.],
       [5., 0.],
       [1., 2.],
       [5., 0.],
       [0., 5.],
       [2., 1.],
       [3., 3.],
       [3., 3.],
       [0., 5.],
       [3., 3.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [3., 3.],
       [3., 3.],
       [5., 0.],
       [3., 3.],
       [5., 0.],
       [3., 3.],
       [1., 2.],
       [0., 5.],
       [5., 0.],
       [5., 0.],
       [0., 5.]])